name: recarga_telefonica_flutter
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  sqflite: ^2.2.8+4
  path: ^1.8.2
  google_fonts: ^4.0.4
  image_picker: ^1.0.4
  image_cropper: ^4.0.1
  lottie: ^2.3.2
  sqflite_common_ffi: ^2.2.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true
  
  assets:
    - assets/
